import Head from 'next/head'
import Header from '../component/Nav'
import Footer from '../component/Footer'
import Link from 'next/link'


import { Button, Card, Grid, Image } from 
'semantic-ui-react'
import photo from '../images/Grumpy.jpg'
import style from '../styles/CatCard.module.css'
import 'semantic-ui-css/semantic.min.css'



export async function getServerSideProps(){
  const res = await fetch('https://catbnb.ml/api');
  const cats = await res.json();

  return {props: {cats}}
}



function Home({cats}) {


  const cat = cats.map(cat => (
    <div key={cat._id} className={style.cardContainer}>
        <Card className={style.card}>
        <Image src={cat.img} wrapped ui={false}/>
        <Card.Content>
            <Card.Header>{cat.name}</Card.Header>
            <Card.Meta>{cat.services}</Card.Meta>
            <Card.Description>Price: {cat.price} catfood/s</Card.Description>
            <Card.Content extra>
                <Link href={`/cats/${cat._id}`} key={cat._id}><a className={style.link}>MORE INFO</a></Link>
            </Card.Content>
        </Card.Content>
    </Card>
    </div>
))

  return (
    <div className={style.body}>
      <Head>
        <title>Genesis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      <div className={style.cardsContainer}>
            {cat} 
      </div>
      <div className={style.dummy}></div>
      <Footer/>
    </div>
  )
}


export default Home