import Head from 'next/head'
import Header from '../component/Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Genesis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel = "icon" href ="logo.svg"  type = "image/x-icon"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet"/>
      </Head>
      <Header/>
    </div>
  )
}
